-- MySQL Script generated by MySQL Workbench
-- Mon Apr 23 19:36:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_cliente` (
  `idusuario_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `correo` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario_cliente`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`residencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`residencia` (
  `idresidencia` INT NOT NULL AUTO_INCREMENT,
  `idusuario_cliente` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `dirreccion` VARCHAR(45) NULL,
  `precio_hora` INT NULL,
  `precio_adicional` INT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idresidencia`),
  INDEX `fk_usuario_cliente_idx` (`idusuario_cliente` ASC),
  CONSTRAINT `fk_usuario_cliente`
    FOREIGN KEY (`idusuario_cliente`)
    REFERENCES `mydb`.`usuario_cliente` (`idusuario_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_empleado` (
  `idusuario_empleado` INT NOT NULL AUTO_INCREMENT,
  `idusuario_cliente` INT NULL,
  `idresidencia` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `cedula` INT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario_empleado`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_usuario_cliente_idx` (`idresidencia` ASC),
  CONSTRAINT `fk_usuario_cliente`
    FOREIGN KEY (`idresidencia`)
    REFERENCES `mydb`.`usuario_cliente` (`idusuario_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_residencia`
    FOREIGN KEY (`idresidencia`)
    REFERENCES `mydb`.`residencia` (`idresidencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `idroles` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `idusuario_cliente` INT NULL,
  `idusuario_empleado` INT NULL,
  `idrol` INT NULL,
  `username` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `hora_seccion` DATETIME NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_empleado_idx` (`idusuario_empleado` ASC),
  INDEX `fk_usuario_cliente_idx` (`idusuario_cliente` ASC),
  INDEX `fk_roles_idx` (`idrol` ASC),
  CONSTRAINT `fk_usuario_empleado`
    FOREIGN KEY (`idusuario_empleado`)
    REFERENCES `mydb`.`usuario_empleado` (`idusuario_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_cliente`
    FOREIGN KEY (`idusuario_cliente`)
    REFERENCES `mydb`.`usuario_cliente` (`idusuario_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles`
    FOREIGN KEY (`idrol`)
    REFERENCES `mydb`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sensor` (
  `idsensor` INT NOT NULL AUTO_INCREMENT,
  `estado_sensor` INT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idsensor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`habitacion` (
  `idhabitacion` INT NOT NULL AUTO_INCREMENT,
  `idresidencia` INT NULL,
  `numero_habitacion` INT NULL,
  `idsensor` INT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idhabitacion`),
  INDEX `fk_residencia_idx` (`idresidencia` ASC),
  INDEX `fk_sensor_idx` (`idsensor` ASC),
  UNIQUE INDEX `numero_habitacion_UNIQUE` (`numero_habitacion` ASC),
  CONSTRAINT `fk_residencia`
    FOREIGN KEY (`idresidencia`)
    REFERENCES `mydb`.`residencia` (`idresidencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sensor`
    FOREIGN KEY (`idsensor`)
    REFERENCES `mydb`.`sensor` (`idsensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ventas` (
  `idventas` INT NOT NULL AUTO_INCREMENT,
  `idempleado` INT NULL,
  `idresidencia` INT NULL,
  `precio` INT NULL,
  `precio_adicional` INT NULL,
  `hora_inicio` DATETIME NULL,
  `hora_final` DATETIME NULL,
  `idhabitacion` INT NULL,
  `estado` VARCHAR(45) NULL,
  `ventascol` VARCHAR(45) NULL,
  PRIMARY KEY (`idventas`),
  INDEX `fk_empleado_idx` (`idempleado` ASC),
  INDEX `fk_residencia_idx` (`idresidencia` ASC),
  INDEX `fk_habitacion_idx` (`idhabitacion` ASC),
  CONSTRAINT `fk_empleado`
    FOREIGN KEY (`idempleado`)
    REFERENCES `mydb`.`usuario_empleado` (`idusuario_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_residencia`
    FOREIGN KEY (`idresidencia`)
    REFERENCES `mydb`.`residencia` (`idresidencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_habitacion`
    FOREIGN KEY (`idhabitacion`)
    REFERENCES `mydb`.`habitacion` (`idhabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
